language: node_js
node_js:
- '10'
dist: trusty
sudo: required
before_install:
- npm install -g yarn
- yarn add @angular/cli@8.3
script:
- ng test -- --no-progress --browsers=ChromeHeadless --watch=false
- ng build --prod --base-href https://maciejjaskolskiportfolio.github.io/notes-app/
deploy:
  provider: heroku
  api_key:
    secure: uIedsv9vmy9mwiFMYDzNP+MTcHT1VVvLNJS5yE0qaQLhEmMcxb09/3G4ra1bxeBnPA1Phnx9Ov9MXMrbqVJGpKFGZAkf19VnL4BPw+Hv0Eh9lm1pPsj9OfC1MIeohsusH4ezjH29nw4iTnGAYEGGyMGfU3PEot4ee9qCUBEUw1XTwaeWK5KZ2PRVh31L42q1SnhzHa+EL+lswMxDTx0A3KsdikOGpVOhQfDcwk6zwf9LobGF+PctUSdL/i7nPYHHT2G88ooWU0zxmlvClk6m/6YNP19RG89r7Fe2twO0vIx3BI6AdLghChLz6NjY6pwXe0U5c7fVxkLVP7igEjtjBCvsN2AL3d/EGLCbA1u+YKI33Xi7JgU4eMlD2x8NGwC5yFH0gBIHXkdXgLSyfIc1COysIm6NO1YvHLXDTJhxCXevjb1ezHYhYzhvjt2gNB23JbNC/c4JDDPyyL9k2TlDGGPRsH+TTF8l2wQjZSZDJ7bOMgil0iFkAUhhZuGQwxdKjTBpjEu0MQcMu2YVaRQ+RgJEajj9JsKodFDfs7t7tjb0k7Cb/0ubWMYFljYxoB52bJwePEn36fjz6REdVKu0urF5rvWpHeWFFTZyXqNDpwuAMuUQrzBTMj2wPP5sTLS5oSdIc843fLUp1Xg5Isa+ZXmgnjPINhzdWPvYOD0VXow=
  app: notesapp-mj
  on:
    branch: master
  skip_cleanup: true
